name: Publish artifacts on Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

permissions:
  contents: write # allows uploading release assets

jobs:
  generate_crd:
    name: Generate CRD
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Generate and Upload CRD
        run: |
          echo "Generating CRD"
          yq '.' crds/*.yaml > crd.yaml
          
          echo "Uploading CRD"
          file=crd.yaml
          upload_url="${{ github.event.release.upload_url }}"
          upload_url=${upload_url%%\{*\}}
          echo "Uploading $file to $upload_url ..."
          curl -sSf \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Content-Type: $(file -b --mime-type $file)" \
            --data-binary @$file \
            "$upload_url?name=$(basename $file)"

  publish_docker:
    name: Publish Docker images
    permissions:
      contents: write # allows uploading release assets from sbom-action
      packages: write
    strategy:
      matrix:
        workload: ["controller", "server", "web-hooks"]
    uses: ./.github/workflows/publish-docker.yaml
    with:
      workload: ${{ matrix.workload }}
    